version: 0.0
os: linux
permissions:
  - object: /home/ec2-user/build
    owner: ec2-user
    group: ec2-user
files:
  - source: .
    destination: /home/ec2-user/build/miau
hooks:
  AfterInstall:
    - location: scripts/checked-build.sh
      timeout: 300
