[package]
name = "miau"
version = "0.1.0"
authors = ["Alex Iadicicco <alex@ajitek.net>"]

[dependencies]
log = "0.3"
toml = "0.3"
bytes = "0.4"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"

[features]
unstable = []  # for travis-cargo
